export { default as Tel } from "./tel.svg";
export { default as Navigation } from "./navigation.svg";
export { default as Shield } from "./shield.svg";
export { default as Notes } from "./notes.svg";
export { default as Star } from "./star.svg";
export { default as Checkmark } from "./checkmark.svg";
export { default as Label } from "./label.svg";
export { default as Wave1 } from "./wave1.svg";
export { default as Wave2 } from "./wave2.svg";
